### ISSUE TITLE
Error: Cannot find module 'event-stream'

### ISSUE THREAD

**Issue by scriptkitz** [hcyang1012/vscode_ctags#2]
```
Error: Cannot find module 'event-stream'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.L.n._load (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:20:23186)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.parse_file_line (C:\Users\Administrator\.vscode\extensions\hcyang.ctags-0.2.4\out\src\file_manager.js:29:14)
    at CTAG_Manager._load_tags (C:\Users\Administrator\.vscode\extensions\hcyang.ctags-0.2.4\out\src\ctag_manager.js:50:22)
    at C:\Users\Administrator\.vscode\extensions\hcyang.ctags-0.2.4\out\src\ctag_manager.js:146:20
    at ChildProcess.exithandler (child_process.js:206:7)
    at emitTwo (events.js:87:13)
```

**Comment by hcyang1012** [comment]
*_Bug accepted. *_
Hi @scriptkitz,
Well, this is because of missing 'event-stream' dependency in package.json. 
I pushed a commit which adds that dependency. 
Could you notify me of whether it works? 
Thanks a lot.
